### ISSUE TITLE
Website is down, mqtt is not

### ISSUE THREAD

**Issue by ecrode** [coldfire84/node-red-alexa-home-skill-v3-web#125]
Tried adding a couple new endpoints, but found that red.cb-net.co.uk is down (according to cloudflare), hope issues are resolved soon, love the service!

**Comment by coldfire84** [comment]
Thanks, this has been an intermittent issue over the last couple of days. I'm hoping I have got to the bottom of it today.

The [MongoDB session handler](https://www.npmjs.com/package/connect-mongo) appears to be at the heart of the issue (still unsure why it has decided after ~2 years to become a problem, total stored sessions was low and there were no DB issues... but hey... :/ ).

I've migrated session management away from MongoDB to [cookie-session](https://www.npmjs.com/package/cookie-session) and this appears, thus far, to have fixed the issue - let me know how you get on.

**Comment by ecrode** [comment]
I can login and manage the devices, thank you! One issue is that I cannot re-enable the alexa skill, after authorization, alexa comes back with this:

![alexa](https://user-images.githubusercontent.com/26380074/88358855-9cc45380-cd3e-11ea-8b75-0cf382173dc2.PNG)

**Comment by paul-e-m** [comment]
I am having this same exact problem. Deleting tokens at https://red.cb-net.co.uk/my-account did not help.

**Comment by coldfire84** [comment]
Yep, I'm working with AWS on trying to get this resolved :( 

Looks to be unrelated to the cookie issues as the OAuth/ account linking pages don't use cookies.

**Comment by coldfire84** [comment]
I think the account linking issue is now resolved, please confirm @ecrode , @madpsintst 

For reference the issue was in the time it was taking for the Amazon Alexa.Authorization OAuth server to respond during account linking (15-20 seconds, whereas this was previously just a second or so!). I've reworked the account linking workflow to accommodate the delay.

Please ensure you "Delete Tokens" under https://red.cb-net.co.uk/my-account

**Comment by ecrode** [comment]
Looks to be working without issues :-) Thank you for everything!

**Comment by paul-e-m** [comment]
Working great now. Thanks!
