### ISSUE TITLE
Add support for en-US

### ISSUE THREAD

**Issue by NovaGL** [coldfire84/node-red-alexa-home-skill-v3-web#5]
My account is set to en-US, is there anyway you could add that to the beta?

I can't discover any devices or see any on node-red and thought that might be why?

**Comment by coldfire84** [comment]
Extended Skill testing availability to:
- English (US)
- English (CA)
- English (AU)
- English (IN)

**Comment by Rapejim** [comment]
Only FYI
I'm using this skill with es-ES configuration in my account without problems (and I speak with Alexa in Spanish, and write the device names ins Spanish). 😅

**Comment by coldfire84** [comment]
@Rapejim would you be happy to assist with #6?

**Comment by coldfire84** [comment]
So the issue is an oath failure on your account. Before I log a support call with Amazon on this can you please:
* Delete both accounts on the bridge (this removes all OAuth tokens etc.)
* Disable the skill on your Amazon Account, thus unlinking
* Create a new account on the bridge, and a device
* Re-link to your Amazon account
