### ISSUE TITLE
NodeRed on Webserver - ‚Alexa device‘ not on a lokal raspberry 

### ISSUE THREAD

**Issue by ConBeeUser** [coldfire84/node-red-alexa-home-skill-v3-web#77]
Hi, thanks a lot for your wonderful NodeRed Plugin! 
This is not an issue but a question, I don‘t know where else I can ask this.

I am Running NodeRed locally on a Raspberry and remote on a server and I would like to outsource as many tasks as possible to the server.

The virtual „Alexa Smart Home“ devices, defined on red.cb-net.co.uk do work fine on the local machine but another ‚Alexa device‘ configured there and set up on the NodeRed instance on the WebServer is not reachable. Is it possible to get this working?
As those devices are configured in the cloud, too (red.cb-net.co.uk) I thought, a cloud instance of this NodeRed plugin should also work because Alexa doesn‘t have to recognise and find the devices locally like it does with those other simpler Alexa plugins for NodeRed (Alexa Home/Alexa local). I thought „red.cb-net.co.uk“ serves as the connection to the configured devices in NodeRed, wherever they might run?

Best Regards
Con

**Comment by coldfire84** [comment]
Hey @ConBeeUser, I'm not sure I fully understand.

Any devices that is configured for this Alexa/ Google Home skill must be defined under 
https://red.cb-net.co.uk/devices and must have a Node-RED node associated with it from the skill. The Node can then be used to control devices on your local network using MQTT or HTTP-based commands, as per the example flows.

You cannot use the skill to control other devices that are linked to your Amazon or Google Home account **via another service**/ skill (although you can co-exist multiple skills such as Philips Hue etc), or that are locally configured (using the local-only skills you mention). Where you are using a local-only/ no cloud device you would need to delete this device configuration and re-create the device via https://red.cb-net.co.uk/devices, due to conflicting device name. Of-course your device then becomes cloud-only, and not local.

Alternatively, you could create a device with a different name via https://red.cb-net.co.uk/devices. 

If I have misunderstood let me know.

**Comment by coldfire84** [comment]
Please re-open when you can supply the additional info.
