### ISSUE TITLE
Logged into foreign account

### ISSUE THREAD

**Issue by 586837r** [coldfire84/node-red-alexa-home-skill-v3-web#82]
When i opened https://red.cb-net.co.uk/ i was already logged into a foreign account.
This happened twice already.

**Comment by coldfire84** [comment]
Looks like something has gone wrong with the CDN rules. I've disabled the CDN for now and purged the cache.

**Comment by coldfire84** [comment]
I've also disabled all/ any NGINX caching as I see the docker container has updated to a newer version recently.

**Comment by coldfire84** [comment]
I have made a few changes to the cookies/ session handler in the most recent commits based upon the configuration recommended for the most recent versions of express-session and connect-mongo libraries.

This issue was reported by two users, although I have been unable to replicate the issue on shared devices/ connections/ browsers.

I'm going to have to re-enable caching to reduce the server bandwidth impact that caching via the CDN offloads. 

If you see this issue again please let me know ASAP via the Slack community here: https://join.slack.com/t/cb-net/shared_invite/enQtODI5OTA2OTEyNDMyLWQwNmQzY2M0NWU3YjQzM2MyOGNhZjU2MTJjYmJjOWEyMDE5NzVmZThlMTI2YmFjNWY0Njc0NGM4ZTY1M2M4NGM

**Comment by coldfire84** [comment]
I have been monitoring sessionID's, IP's and usernames for the last 48 hours, with CDN caching re-enabled. No issues of sessionIDs being (re)used across unauthenticated or authenticated sessions and IP addresses.
